BEGIN;

ALTER TABLE ebock.item
    ADD COLUMN deleted_at TIMESTAMPTZ DEFAULT NULL;

ALTER TABLE ebock.item DROP COLUMN archived;

ALTER TABLE ebock.order_
    ADD COLUMN archived_at TIMESTAMPTZ DEFAULT NULL;

COMMIT;
